/**
 * Embeds src/audio-processor.js as a string in src/audioProcessorSource.generated.ts
 * so the worklet can be loaded via a Blob URL at runtime (no separate hosting).
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const workletPath = join(root, 'src', 'audio-processor.js');
const outPath = join(root, 'src', 'audioProcessorSource.generated.ts');

const content = readFileSync(workletPath, 'utf8');
const escaped = JSON.stringify(content);

const ts = `/** Generated by scripts/embed-worklet.mjs - do not edit */
export const audioProcessorSource = ${escaped};
`;

writeFileSync(outPath, ts);
console.log('Embedded worklet source into src/audioProcessorSource.generated.ts');
